### ISSUE TITLE
Create Initial Shiny App

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/budget_app#3]
# Overview

This may get broken up into multiple issues at some point in the future.

Currently, you are using [Google Sheets](https://docs.google.com/spreadsheets/d/1WwseDMbA9OTkwhb51wMKgJfVlayhp-j65tf7MYfwhZ4/edit#gid=1109763561) as your budgeting app. It works ok, but you you may want to create more of a database-like solution. 

## Useful links

- [SQL diagram](https://drawsql.app/teams/brad-cannells-team/diagrams/budget-bill-pay-view)
- [Wiki notes about paying bills](https://github.com/brad-cannell/budget_app/wiki/Pay-Bills)
- [Example Shiny database frontend](https://shanghai.hosting.nyu.edu/data/r/case-4-database-management-shiny.html)

## Other considerations

- Is there a USAA API I can use to pull in account information directly from USAA?

# Tasks

- [x] Create the home page
- [ ] Complete the code to create the `bill_pay` data frame. I'm thinking this will be the table I use when I'm paying bills (#10).
- [ ] Create an interactive Shiny interface for paying bills.

**Comment by mbcann01** [comment]
2023-03-24

- Left off working [bill pay functionality](https://github.com/brad-cannell/budget_app/wiki/Pay-Bills).
- Right now, I'm just trying to put together the bill pay table in a non-interactive way (`bills_due.R`).
- I need to get a clearer idea of what the end goal is. 

Copy and paste for commits:

````
Working on bill pay table
Part of #3
- Create a non-interactive combined bill pay table in bills_due.R
````
